"""The engine behind `agentbricks models upgrade`: search models and prompts for an agent.

The search always runs on Databricks, as a serverless job — never on the developer's machine, since
it can take hours. `models upgrade` syncs the project to a workspace folder, uploads a small runner,
and submits a one-time run (``submit_upgrade_run``) whose environment installs the project (a
Python project in workspace files) plus ``databricks-agentbricks[upgrade]``. Inside the job,
``job_main`` imports the project's own ``predict_fn``, eval data, and scorers (``module:attr``
references, the same inputs ``optimize_prompts_and_models`` takes) and runs the search:
``databricks_agentkit.model_upgrades.optimize_prompts_and_models`` (GEPA), which routes the agent's
calls to a temporary ``<service>_exp`` clone of the bound model service, so production traffic is
never touched while candidates run. The job records its ``UpgradeReport`` on an MLflow run; the CLI
reads it back (``fetch_report``) and only `models apply` switches the service.

The job-side heavy dependencies (``gepa``, full ``mlflow``) are imported lazily, so the CLI stays
light.
"""

from __future__ import annotations

import dataclasses
import importlib
import json
import os
import pathlib
import sys
import time
from collections.abc import Sequence
from dataclasses import dataclass, field
from typing import Any, Optional

from databricks_agentbricks.errors import AgentCliError
from databricks_agentkit.runtime.model_services import system_ai_name
from databricks_agentkit.runtime.tool_manifest import model_service_env

UPGRADE_EXTRA_HINT = "Install it with: pip install 'databricks-agentbricks[upgrade]'"
# Upgrade-run history (for `models status` / `models rollback`), next to the project metadata.
HISTORY_PATH = pathlib.Path(".agentbricks/model_upgrades.json")
# Serverless environment the job runs in (Python 3.12; the templates need >= 3.11).
SERVERLESS_ENVIRONMENT_VERSION = "5"
# The `databricks-agentbricks` requirement the job installs. Defaults to this CLI's own version;
# override (e.g. with a git URL) to run an unreleased build.
UPGRADE_REQUIREMENT_ENV = "AGENTBRICKS_UPGRADE_REQUIREMENT"
DEFAULT_TIMEOUT_HOURS = 6
# MLflow tags on the job's run: the id the CLI looks the run up by, and the report itself.
UPGRADE_ID_TAG = "agentbricks.upgrade_id"
REPORT_TAG = "agentbricks.upgrade_report"
# The optimizer's Result, saved on the job's run so `models apply` can hand it to `promote_to_prod`,
# which repoints every changed model service and registers the winning prompts together.
PROMOTION_ARTIFACT = "promotion.json"
_RUNNER = """# Generated by `agentbricks models upgrade`; runs the model search inside a Databricks job.
import os
import sys

# psycopg[binary] bundles its own OpenSSL, which aborts the process (FATAL FIPS SELFTEST FAILURE) on
# FIPS-enabled compute. The search never touches Lakebase, so use the image's system libpq instead.
# Must be set before anything imports psycopg (the templates do, via databricks_langchain).
os.environ.setdefault("PSYCOPG_IMPL", "python")

from databricks_agentbricks.model_upgrade import job_main

job_main(sys.argv[1:])
"""
_SYSTEM_AI = "system.ai."


@dataclass
class ServiceRecommendation:
    """One bound model service's result: the model it routes to now, and the one that won."""

    service: str
    current_model: str
    recommended_model: str
    # Best validation score GEPA saw with each model behind this service, for the comparison table.
    model_scores: dict[str, float] = field(default_factory=dict)

    @property
    def changed(self) -> bool:
        return self.recommended_model != self.current_model


@dataclass
class UpgradeReport:
    """What `models upgrade` found: a recommendation per bound role, plus the prompts it rewrote."""

    recommendations: dict[str, ServiceRecommendation]
    baseline_score: float
    best_score: float
    train_records: int = 0
    val_records: int = 0
    # Prompts (registry names) the winner rewrote; empty when only models changed.
    prompt_changes: list[str] = field(default_factory=list)
    mlflow_run_id: Optional[str] = None

    @property
    def changed(self) -> bool:
        return any(r.changed for r in self.recommendations.values()) or bool(self.prompt_changes)

    @classmethod
    def from_json(cls, data: dict[str, Any]) -> "UpgradeReport":
        return cls(
            recommendations={
                role: ServiceRecommendation(
                    service=rec["model_service"],
                    current_model=rec["current_model"],
                    recommended_model=rec["recommended_model"],
                    model_scores={k: float(v) for k, v in (rec.get("model_scores") or {}).items()},
                )
                for role, rec in data["recommendations"].items()
            },
            baseline_score=float(data["baseline_score"]),
            best_score=float(data["best_score"]),
            train_records=int(data.get("train_records", 0)),
            val_records=int(data.get("val_records", 0)),
            prompt_changes=list(data.get("prompt_changes") or []),
            mlflow_run_id=data.get("mlflow_run_id"),
        )

    def to_json(self) -> dict[str, Any]:
        return {
            "recommendations": {
                role: {
                    "model_service": rec.service,
                    "current_model": rec.current_model,
                    "recommended_model": rec.recommended_model,
                    "changed": rec.changed,
                    "model_scores": rec.model_scores,
                }
                for role, rec in self.recommendations.items()
            },
            "changed": self.changed,
            "baseline_score": self.baseline_score,
            "best_score": self.best_score,
            "train_records": self.train_records,
            "val_records": self.val_records,
            "prompt_changes": self.prompt_changes,
            "mlflow_run_id": self.mlflow_run_id,
        }


# --- model names ----------------------------------------------------------------


def bare_name(model: str) -> str:
    """The optimizer's model key: the ``system.ai.*`` name without its schema prefix."""
    return model.removeprefix(_SYSTEM_AI)


# --- the search (runs inside the job) --------------------------------------------


def _optimizer():
    try:
        from databricks_agentkit import model_upgrades  # noqa: PLC0415 - needs gepa + full mlflow
    except ImportError as exc:
        raise AgentCliError(
            "The model search requires the 'upgrade' extra.", hint=UPGRADE_EXTRA_HINT
        ) from exc
    return model_upgrades


def load_object(root: pathlib.Path, ref: str) -> Any:
    """The object ``module:attr`` names, imported from the project at ``root``."""
    module_name, _, attr = ref.partition(":")
    if not module_name or not attr:
        raise AgentCliError(f"'{ref}' isn't a module:attr reference (e.g. agent.eval:predict).")
    if str(root) not in sys.path:
        sys.path.insert(0, str(root))
    try:
        return getattr(importlib.import_module(module_name), attr)
    except (ImportError, AttributeError) as exc:
        raise AgentCliError(
            f"Could not load {ref} from the project: {exc}.",
            hint="The job installs the project from its pyproject.toml; declare its dependencies "
            "there.",
        ) from exc


def _model_scores(result: Any, service: str) -> dict[str, float]:
    """Best validation score GEPA saw per model, for the comparison table (empty if unavailable)."""
    gepa_result = getattr(result, "gepa_result", None)
    candidates = getattr(gepa_result, "candidates", None) or []
    scores = getattr(gepa_result, "val_aggregate_scores", None) or []
    best: dict[str, float] = {}
    for candidate, score in zip(candidates, scores):
        model = candidate.get(f"model:{service}") if isinstance(candidate, dict) else None
        if model is None:
            continue
        key = system_ai_name(model)
        best[key] = max(best.get(key, float("-inf")), float(score))
    return best


def upgrade_experiment_name(trace_experiment: str) -> str:
    """Where upgrade runs log: a sibling of the agent's trace experiment, never the experiment itself,
    so search traffic never mixes with production traces."""
    return f"{trace_experiment}-model-upgrades"


def run_upgrade(
    *,
    services: dict[str, str],
    current_models: dict[str, str],
    candidates: dict[str, list[str]],
    prompt_uris: Sequence[str],
    predict_fn: Any,
    train_data: list,
    val_data: list,
    scorers: list,
    budget: Optional[int],
    weights: tuple[float, float, float],
) -> tuple[UpgradeReport, Any]:
    """Search every bound role's candidates (plus its current model) and ``prompt_uris`` jointly.

    ``services`` maps role → model service; roles with no candidates keep their current model and
    aren't searched. Returns the report and the optimizer's ``Result``.
    """
    optimizer = _optimizer()
    weight_quality, weight_latency, weight_cost = weights
    result = optimizer.optimize_prompts_and_models(
        predict_fn,
        train_data,
        val_data,
        prompt_uris=list(prompt_uris),
        gateway_endpoints={
            services[role]: [bare_name(m) for m in models]
            for role, models in candidates.items()
            if models
        },
        scorers=scorers,
        max_metric_calls=budget or 4 * (len(train_data) + len(val_data)),
        weight_quality=weight_quality,
        weight_latency=weight_latency,
        weight_cost=weight_cost,
        model_selection="bandit",
        display_progress_bar=False,
    )
    recommendations = {}
    for role, service in services.items():
        current = current_models[role]
        winner = result.best_candidate.get(f"model:{service}") or bare_name(current)
        recommendations[role] = ServiceRecommendation(
            service=service,
            current_model=system_ai_name(current),
            recommended_model=system_ai_name(winner),
            model_scores=_model_scores(result, service),
        )
    prompt_changes = [
        target.name
        for target in result.prompt_targets
        if result.best_candidate.get(f"prompt:{target.short_name}") not in (None, target.template)
    ]
    report = UpgradeReport(
        recommendations=recommendations,
        baseline_score=float(result.baseline_score),
        best_score=float(result.best_score),
        train_records=len(train_data),
        val_records=len(val_data),
        prompt_changes=prompt_changes,
    )
    return report, result


def promotion_payload(result: Any) -> dict[str, Any]:
    """The optimizer ``Result`` as JSON, minus the raw GEPA result (which isn't serializable)."""
    return {
        "best_candidate": result.best_candidate,
        "best_score": result.best_score,
        "baseline_score": result.baseline_score,
        "prompt_uris": result.prompt_uris,
        "gateway_endpoints": result.gateway_endpoints,
        "prompt_targets": [dataclasses.asdict(t) for t in result.prompt_targets],
        "endpoint_targets": [dataclasses.asdict(t) for t in result.endpoint_targets],
    }


def load_promotion(run_id: str) -> Any:
    """Rebuild the optimizer ``Result`` a job saved on MLflow run ``run_id``."""
    import mlflow  # noqa: PLC0415 - upgrade-extra dependency

    from databricks_agentkit.model_upgrades import optimization  # noqa: PLC0415

    data = mlflow.artifacts.load_dict(f"runs:/{run_id}/{PROMOTION_ARTIFACT}")
    data["prompt_targets"] = [optimization._PromptTarget(**t) for t in data["prompt_targets"]]
    data["endpoint_targets"] = [optimization._EndpointTarget(**t) for t in data["endpoint_targets"]]
    return optimization.Result(**data)


@dataclass
class JobConfig:
    """Everything the job needs, passed to the runner as one JSON parameter."""

    upgrade_id: str
    services: dict[str, str]
    candidates: dict[str, list[str]]
    prompt_uris: list[str]
    predict_fn: str
    train_data: str
    val_data: str
    scorers: list[str]
    trace_experiment: str
    budget: Optional[int]
    weights: tuple[float, float, float]

    def to_param(self) -> str:
        return json.dumps({**self.__dict__, "weights": list(self.weights)})

    @classmethod
    def from_param(cls, raw: str) -> "JobConfig":
        data = json.loads(raw)
        data["weights"] = tuple(data["weights"])
        return cls(**data)


def _load_scorers(root: pathlib.Path, refs: Sequence[str]) -> list:
    """Each ref names a scorer or a list of them; flattened into one list."""
    scorers: list = []
    for ref in refs:
        loaded = load_object(root, ref)
        scorers.extend(loaded if isinstance(loaded, (list, tuple)) else [loaded])
    return scorers


def job_main(argv: Sequence[str]) -> None:
    """The job's entrypoint: ``<project root> <JobConfig JSON>``. Records the report on an MLflow run."""
    import mlflow  # noqa: PLC0415 - job-side dependency

    from databricks_agentkit.runtime import model_services  # noqa: PLC0415
    from databricks_agentkit.runtime.workspace import workspace_client  # noqa: PLC0415

    root, config = pathlib.Path(argv[0]), JobConfig.from_param(argv[1])
    # Each call site must call its bound service (the agent reads AGENT_MODEL_SERVICE_<ROLE> at
    # import), or the optimizer's redirect to the <service>_exp clone never matches.
    for role, service in config.services.items():
        os.environ[model_service_env(role)] = service
    mlflow.set_tracking_uri("databricks")
    mlflow.set_experiment(upgrade_experiment_name(config.trace_experiment))
    with mlflow.start_run(run_name=f"model-upgrade-{config.upgrade_id}") as run:
        mlflow.set_tags(
            {
                UPGRADE_ID_TAG: config.upgrade_id,
                "agentbricks.model_services": ",".join(config.services.values()),
            }
        )
        mlflow.log_params(
            {
                "candidates": json.dumps(config.candidates),
                "prompt_uris": ",".join(config.prompt_uris),
                "predict_fn": config.predict_fn,
                "scorers": ",".join(config.scorers),
                "budget": config.budget or "auto",
                "weights": ",".join(str(w) for w in config.weights),
            }
        )
        client = workspace_client()
        report, result = run_upgrade(
            services=config.services,
            current_models={
                role: model_services.get_model(client, service)
                for role, service in config.services.items()
            },
            candidates=config.candidates,
            prompt_uris=config.prompt_uris,
            predict_fn=load_object(root, config.predict_fn),
            train_data=list(load_object(root, config.train_data)),
            val_data=list(load_object(root, config.val_data)),
            scorers=_load_scorers(root, config.scorers),
            budget=config.budget,
            weights=config.weights,
        )
        report.mlflow_run_id = run.info.run_id
        mlflow.log_dict(promotion_payload(result), PROMOTION_ARTIFACT)
        mlflow.set_tag(REPORT_TAG, json.dumps(report.to_json()))
        print(f"Upgrade report (MLflow run {run.info.run_id}): {json.dumps(report.to_json())}")


# --- submitting and reading back (CLI side) ------------------------------------------


def upgrade_requirement() -> str:
    """The `databricks-agentbricks` requirement the job installs: this CLI's version unless overridden."""
    override = os.getenv(UPGRADE_REQUIREMENT_ENV)
    if override:
        return override
    from importlib.metadata import version  # noqa: PLC0415

    return f"databricks-agentbricks[upgrade]=={version('databricks-agentbricks')}"


def workspace_project_path(user: str, project_name: str) -> str:
    """Where `models upgrade` syncs the project: its own folder, never the deployed app's source."""
    return f"/Workspace/Users/{user}/agentbricks_model_upgrades/{project_name}"


def submit_upgrade_run(
    client,
    *,
    workspace_path: str,
    config: JobConfig,
    timeout_hours: float = DEFAULT_TIMEOUT_HOURS,
) -> tuple[int, Optional[str]]:
    """Upload the runner and submit the serverless one-time run. Returns ``(run_id, run_page_url)``.

    The project must already be synced to ``workspace_path``.
    """
    runner_path = f"{workspace_path}/.agentbricks/model_upgrade_job.py"
    client.upload_workspace_file(runner_path, _RUNNER)
    run_id = client.submit_serverless_python_run(
        run_name=f"agentbricks models upgrade · {', '.join(config.services.values())}",
        python_file=runner_path,
        parameters=[workspace_path, config.to_param()],
        dependencies=[workspace_path, upgrade_requirement()],
        environment_version=SERVERLESS_ENVIRONMENT_VERSION,
        timeout_seconds=int(timeout_hours * 3600),
        tags={UPGRADE_ID_TAG.replace(".", "_"): config.upgrade_id},
    )
    run = client.get_run(run_id)
    return run_id, getattr(run, "run_page_url", None)


def fetch_report(
    profile: Optional[str], trace_experiment: str, upgrade_id: str
) -> Optional[UpgradeReport]:
    """The report a finished job recorded on its MLflow run, or None if it hasn't recorded one."""
    from databricks_agentbricks.cli import tracing  # noqa: PLC0415 - avoid import cycle

    mlflow = tracing._mlflow()
    tracing._set_tracking_uri(mlflow, profile)
    runs = mlflow.search_runs(
        experiment_names=[upgrade_experiment_name(trace_experiment)],
        filter_string=f"tags.`{UPGRADE_ID_TAG}` = '{upgrade_id}'",
        output_format="list",
    )
    for run in runs:
        raw = run.data.tags.get(REPORT_TAG)
        if raw:
            return UpgradeReport.from_json(json.loads(raw))
    return None


# --- history (runs, switches, rollback) ---------------------------------------------


_HISTORY_KEYS = ("runs", "changes", "actions")


def read_history(root: pathlib.Path) -> dict[str, list[dict[str, Any]]]:
    """The project's upgrade history.

    ``runs`` are submitted upgrade jobs, ``changes`` are individual model-service repoints, and
    ``actions`` are what `models rollback` undoes: one entry per `apply` or `set`, holding every
    model switch and prompt-alias move it made.
    """
    path = root / HISTORY_PATH
    try:
        history = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return {key: [] for key in _HISTORY_KEYS}
    except (OSError, json.JSONDecodeError) as exc:
        raise AgentCliError(f"Could not read model upgrade history at {path}: {exc}.") from exc
    if not isinstance(history, dict):
        return {key: [] for key in _HISTORY_KEYS}
    return {key: list(history.get(key) or []) for key in _HISTORY_KEYS}


def _write_history(root: pathlib.Path, history: dict[str, list[dict[str, Any]]]) -> None:
    path = root / HISTORY_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(history, indent=2) + "\n", encoding="utf-8")


def record_run(root: pathlib.Path, entry: dict[str, Any]) -> None:
    """Append one submitted upgrade run."""
    history = read_history(root)
    history["runs"].append({"timestamp": int(time.time()), **entry})
    _write_history(root, history)


def update_run(root: pathlib.Path, upgrade_id: str, **fields: Any) -> None:
    """Merge ``fields`` into the recorded run ``upgrade_id`` (e.g. its final state and report)."""
    history = read_history(root)
    for run in history["runs"]:
        if run.get("upgrade_id") == upgrade_id:
            run.update(fields)
    _write_history(root, history)


def record_change(
    root: pathlib.Path,
    *,
    service: str,
    previous: Optional[str],
    model: str,
    reason: str,
    report: Optional[UpgradeReport] = None,
) -> None:
    """Append one repoint of ``service`` (``previous`` → ``model``) to the project's history."""
    entry: dict[str, Any] = {
        "timestamp": int(time.time()),
        "model_service": service,
        "previous_model": previous,
        "model": model,
        "reason": reason,
    }
    if report is not None:
        entry["baseline_score"] = report.baseline_score
        entry["best_score"] = report.best_score
    history = read_history(root)
    history["changes"].append(entry)
    _write_history(root, history)


def record_action(
    root: pathlib.Path,
    kind: str,
    *,
    models: Sequence[dict[str, Any]],
    prompts: Sequence[dict[str, Any]] = (),
) -> None:
    """Append one undoable action: ``models`` as {model_service, previous_model, model}, ``prompts``
    as {name, alias, prior_version} (the version the alias pointed at before the action)."""
    history = read_history(root)
    history["actions"].append(
        {
            "timestamp": int(time.time()),
            "kind": kind,
            "models": list(models),
            "prompts": list(prompts),
            "rolled_back": False,
        }
    )
    _write_history(root, history)


def last_undoable_action(root: pathlib.Path) -> Optional[tuple[int, dict[str, Any]]]:
    """``(index, action)`` of the latest action not yet rolled back, or None."""
    for index, action in reversed(list(enumerate(read_history(root)["actions"]))):
        if not action.get("rolled_back"):
            return index, action
    return None


def mark_rolled_back(root: pathlib.Path, index: int) -> None:
    history = read_history(root)
    history["actions"][index]["rolled_back"] = True
    _write_history(root, history)
