"""The engine behind `agentbricks models upgrade`: evaluate candidate models on an agent's own traces.

The search always runs on Databricks, as a serverless job — never on the developer's machine, since
it can take hours. `models upgrade` syncs the project to a workspace folder, uploads a small runner,
and submits a one-time run (``submit_upgrade_run``) whose environment installs the project (a
Python project in workspace files) plus ``databricks-agentbricks[upgrade]``. Inside the job,
``job_main`` replays the agent's recent production requests (root ``invoke`` spans from its bound
trace experiment) through the project's own agent code, once per candidate model, and scores each
answer against what production returned with an LLM judge. The search is
``databricks_agentkit.model_upgrades.optimize_prompts_and_models`` (GEPA), which routes the agent's
calls to a temporary ``<service>_exp`` clone of the bound model service, so production traffic is
never touched while candidates run. The job records its ``UpgradeReport`` on an MLflow run; the CLI
reads it back (``fetch_report``) and only `models apply` switches the service.

The job-side heavy dependencies (``gepa``, full ``mlflow``) are imported lazily, so the CLI stays
light.
"""

from __future__ import annotations

import asyncio
import importlib
import json
import os
import pathlib
import re
import sys
import time
import uuid
from collections.abc import Callable, Sequence
from dataclasses import dataclass, field
from typing import Any, Optional

from databricks_agentbricks.errors import AgentCliError
from databricks_agentbricks.project_types import AgentFramework
from databricks_agentkit.runtime.model_services import system_ai_name
from databricks_agentkit.runtime.tool_manifest import MODEL_SERVICE_ENV

UPGRADE_EXTRA_HINT = "Install it with: pip install 'databricks-agentbricks[upgrade]'"
# Upgrade-run history (for `models status` / `models rollback`), next to the project metadata.
HISTORY_PATH = pathlib.Path(".agentbricks/model_upgrades.json")
DEFAULT_JUDGE_MODEL = "databricks-claude-sonnet-4-6"
# Serverless environment the job runs in (Python 3.12; the templates need >= 3.11).
SERVERLESS_ENVIRONMENT_VERSION = "5"
# The `databricks-agentbricks` requirement the job installs. Defaults to this CLI's own version;
# override (e.g. with a git URL) to run an unreleased build.
UPGRADE_REQUIREMENT_ENV = "AGENTBRICKS_UPGRADE_REQUIREMENT"
DEFAULT_TIMEOUT_HOURS = 6
# MLflow tags on the job's run: the id the CLI looks the run up by, and the report itself.
UPGRADE_ID_TAG = "agentbricks.upgrade_id"
REPORT_TAG = "agentbricks.upgrade_report"
_RUNNER = """# Generated by `agentbricks models upgrade`; runs the model search inside a Databricks job.
import sys

from databricks_agentbricks.model_upgrade import job_main

job_main(sys.argv[1:])
"""
# Below this many usable traces the train/val split is too small to say anything.
MIN_RECORDS = 5

_SYSTEM_AI = "system.ai."
_JUDGE_PROMPT = """You are grading an AI agent's answer against a reference answer that the agent's \
current production model gave for the same request.

Request:
{request}

Reference answer (production):
{reference}

Candidate answer:
{candidate}

How well does the candidate answer the request compared to the reference? 1 means at least as \
good (correct, complete, helpful); 0 means wrong or unhelpful. Partial credit is allowed.
Reply with only a number between 0 and 1."""


@dataclass
class UpgradeReport:
    """What `models upgrade` found: the recommendation plus per-model scores for the table."""

    service: str
    current_model: str
    recommended_model: str
    baseline_score: float
    best_score: float
    model_scores: dict[str, float] = field(default_factory=dict)
    train_records: int = 0
    val_records: int = 0

    @property
    def changed(self) -> bool:
        return self.recommended_model != self.current_model

    @classmethod
    def from_json(cls, data: dict[str, Any]) -> "UpgradeReport":
        return cls(
            service=data["model_service"],
            current_model=data["current_model"],
            recommended_model=data["recommended_model"],
            baseline_score=float(data["baseline_score"]),
            best_score=float(data["best_score"]),
            model_scores={k: float(v) for k, v in (data.get("model_scores") or {}).items()},
            train_records=int(data.get("train_records", 0)),
            val_records=int(data.get("val_records", 0)),
        )

    def to_json(self) -> dict[str, Any]:
        return {
            "model_service": self.service,
            "current_model": self.current_model,
            "recommended_model": self.recommended_model,
            "changed": self.changed,
            "baseline_score": self.baseline_score,
            "best_score": self.best_score,
            "model_scores": self.model_scores,
            "train_records": self.train_records,
            "val_records": self.val_records,
        }


# --- model names ----------------------------------------------------------------


def bare_name(model: str) -> str:
    """The optimizer's model key: the ``system.ai.*`` name without its schema prefix."""
    return model.removeprefix(_SYSTEM_AI)


# --- answers --------------------------------------------------------------------

_ASSISTANT_ROLES = {"assistant", "ai"}


def _content_text(content: Any) -> str:
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts = [
            block.get("text", "") if isinstance(block, dict) else str(block) for block in content
        ]
        return "".join(part for part in parts if part)
    return "" if content is None else str(content)


def final_text(value: Any) -> str:
    """The agent's final answer text from a run output, a trace response, or a message list.

    Handles both templates' shapes: the OpenAI Agents ``{"output": final_output}`` and the LangGraph
    last ``updates`` payload (``{node: {"messages": [...]}}``, as message objects or their dumps).
    The last assistant message wins; tool, user, and system messages are skipped.
    """
    if value is None:
        return ""
    if isinstance(value, str):
        return value
    if isinstance(value, (list, tuple)):
        for item in reversed(value):
            text = final_text(item)
            if text:
                return text
        return ""
    if isinstance(value, dict):
        role = value.get("role") or value.get("type")
        if "content" in value and role is not None:
            return _content_text(value["content"]) if role in _ASSISTANT_ROLES else ""
        if "output" in value:
            return final_text(value["output"])
        if "messages" in value:
            return final_text(value["messages"])
        return final_text(list(value.values()))
    role = getattr(value, "type", None) or getattr(value, "role", None)
    if hasattr(value, "content"):
        return _content_text(value.content) if role in _ASSISTANT_ROLES else ""
    return str(value)


# --- eval set from traces -------------------------------------------------------


def _loads(raw: Any) -> Any:
    if isinstance(raw, str):
        try:
            return json.loads(raw)
        except json.JSONDecodeError:
            return raw
    return raw


def records_from_traces(traces: Sequence[Any]) -> list[dict[str, Any]]:
    """Turn traces into optimizer records: the agent's input, and production's answer as reference.

    Only successful traces with a non-empty request and answer are kept. The input is carried
    verbatim under ``agent_input`` so the replay hands the agent exactly what production received.
    """
    records = []
    for trace in traces:
        info = getattr(trace, "info", None)
        state = str(getattr(info, "state", None) or getattr(info, "status", None) or "")
        if state and "OK" not in state.upper():
            continue
        data = getattr(trace, "data", None)
        request = _loads(getattr(data, "request", None))
        reference = final_text(_loads(getattr(data, "response", None)))
        if not request or not reference:
            continue
        records.append(
            {
                "inputs": {"agent_input": request},
                "expectations": {"expected_response": reference},
            }
        )
    return records


def split_records(records: list[dict[str, Any]]) -> tuple[list[dict], list[dict]]:
    """Split into (train, val): about 30% validation, at least two records on each side."""
    if len(records) < MIN_RECORDS:
        raise AgentCliError(
            f"Found {len(records)} usable traces; models upgrade needs at least {MIN_RECORDS}.",
            hint="Send the deployed agent more traffic (or raise --traces), then retry.",
        )
    val_size = min(max(2, round(len(records) * 0.3)), len(records) - 2)
    return records[val_size:], records[:val_size]


def load_traces(profile: Optional[str], experiment_name: str, limit: int) -> list[Any]:
    """The most recent ``limit`` traces from the bound workspace trace experiment."""
    from databricks_agentbricks.cli import tracing  # noqa: PLC0415 - avoid import cycle

    mlflow = tracing._mlflow()
    tracing._set_tracking_uri(mlflow, profile)
    experiment = mlflow.get_experiment_by_name(experiment_name)
    if experiment is None:
        raise AgentCliError(
            f"Trace experiment '{experiment_name}' doesn't exist in this workspace yet.",
            hint="Deploy the agent (`agentbricks deploy`) and send it traffic first.",
        )
    return mlflow.search_traces(
        locations=[experiment.experiment_id], max_results=limit, return_type="list"
    )


# --- replaying the agent --------------------------------------------------------


def make_predict_fn(
    root: pathlib.Path, framework: AgentFramework, service: str
) -> Callable[[dict], str]:
    """A sync ``predict(inputs) -> answer`` that runs the project's own agent in-process.

    The agent must call ``service`` (the templates read it from ``AGENT_MODEL_SERVICE`` at import), or
    the optimizer's redirect to the ``<service>_exp`` clone never matches and every candidate would
    be scored on the template's default model. Each call gets a fresh session id. No session or
    memory store env is set for the replay, so the templates fall back to an in-memory checkpointer
    and no memory tools: replays never read or write production state.
    """
    os.environ[MODEL_SERVICE_ENV] = service
    os.environ.setdefault("AGENTBRICKS_PROJECT_ROOT", str(root))
    if str(root) not in sys.path:
        sys.path.insert(0, str(root))
    try:
        agent_module = importlib.import_module("agent.agent")
    except ImportError as exc:
        raise AgentCliError(
            f"Could not import the agent from {root / 'agent' / 'agent.py'}: {exc}.",
            hint="The job installs the project from its pyproject.toml; declare the agent's "
            "dependencies there.",
        ) from exc
    run_agent = agent_module.run_agent
    _enable_autolog(framework)

    if framework == AgentFramework.LANGGRAPH:

        async def _run(agent_input: Any) -> Any:
            last = None
            async for event in run_agent(agent_input, session_id=uuid.uuid4().hex):
                if isinstance(event, tuple) and event and event[0] == "updates":
                    last = event[1]
            return last

    else:

        async def _run(agent_input: Any) -> Any:
            async with run_agent(agent_input, session_id=uuid.uuid4().hex) as result:
                async for _ in result.stream_events():
                    pass
            return result.final_output

    def predict(inputs: dict) -> str:
        return final_text(asyncio.run(_run(inputs["agent_input"])))

    return predict


def _enable_autolog(framework: AgentFramework) -> None:
    """Turn on the framework's MLflow autolog so the optimizer prices candidates on real tokens.

    The templates only enable it in ``configure()`` at server startup, which the replay skips; without
    it every call is priced at a flat 500/200-token estimate and the cost component can't tell a
    terse model from a verbose one.
    """
    import mlflow  # noqa: PLC0415 - heavy optional dependency

    if framework == AgentFramework.LANGGRAPH:
        mlflow.langchain.autolog()
    else:
        mlflow.openai.autolog()


# --- scoring --------------------------------------------------------------------


def make_equivalence_scorer(judge_model: str = DEFAULT_JUDGE_MODEL) -> Callable[..., float]:
    """An LLM judge scoring a candidate answer against production's answer, 0 to 1. No labels needed."""
    from databricks.sdk import WorkspaceClient  # noqa: PLC0415

    client = WorkspaceClient().serving_endpoints.get_open_ai_client()

    def equivalence(inputs: dict, expectations: dict, answer: Any) -> float:
        prompt = _JUDGE_PROMPT.format(
            request=json.dumps(inputs.get("agent_input"), default=str)[:4000],
            reference=str(expectations.get("expected_response", ""))[:4000],
            candidate=str(answer)[:4000],
        )
        response = client.chat.completions.create(
            model=judge_model, messages=[{"role": "user", "content": prompt}]
        )
        text = response.choices[0].message.content or ""
        match = re.search(r"(?<![\d.])(?:0(?:\.\d+)?|1(?:\.0+)?)(?![\d.])", text)
        if match is None:
            raise ValueError(f"judge returned no score: {text[:80]!r}")
        return float(match.group())

    return equivalence


# --- the search (runs inside the job) --------------------------------------------


def _optimizer():
    try:
        from databricks_agentkit import model_upgrades  # noqa: PLC0415 - needs gepa + full mlflow
    except ImportError as exc:
        raise AgentCliError(
            "The model search requires the 'upgrade' extra.", hint=UPGRADE_EXTRA_HINT
        ) from exc
    return model_upgrades


def _model_scores(result: Any, service: str) -> dict[str, float]:
    """Best validation score GEPA saw per model, for the comparison table (empty if unavailable)."""
    gepa_result = getattr(result, "gepa_result", None)
    candidates = getattr(gepa_result, "candidates", None) or []
    scores = getattr(gepa_result, "val_aggregate_scores", None) or []
    best: dict[str, float] = {}
    for candidate, score in zip(candidates, scores):
        model = candidate.get(f"model:{service}") if isinstance(candidate, dict) else None
        if model is None:
            continue
        key = system_ai_name(model)
        best[key] = max(best.get(key, float("-inf")), float(score))
    return best


def upgrade_experiment_name(trace_experiment: str) -> str:
    """Where upgrade runs log: a sibling of the agent's trace experiment, never the experiment itself,
    or the next upgrade would train on this one's replay traffic."""
    return f"{trace_experiment}-model-upgrades"


def run_upgrade(
    *,
    root: pathlib.Path,
    framework: AgentFramework,
    service: str,
    current_model: str,
    candidates: Sequence[str],
    traces: Sequence[Any],
    budget: Optional[int],
    judge_model: str,
    weights: tuple[float, float, float],
) -> UpgradeReport:
    """Search ``candidates`` (plus the current model) for the best model behind ``service``."""
    optimizer = _optimizer()
    train, val = split_records(records_from_traces(traces))
    predict = make_predict_fn(root, framework, service)
    scorer = make_equivalence_scorer(judge_model)
    weight_quality, weight_latency, weight_cost = weights
    result = optimizer.optimize_prompts_and_models(
        predict,
        train,
        val,
        gateway_endpoints={service: [bare_name(m) for m in candidates]},
        scorers=[scorer],
        max_metric_calls=budget or 4 * (len(train) + len(val)),
        weight_quality=weight_quality,
        weight_latency=weight_latency,
        weight_cost=weight_cost,
        model_selection="bandit",
        display_progress_bar=False,
    )
    winner = result.best_candidate.get(f"model:{service}") or bare_name(current_model)
    return UpgradeReport(
        service=service,
        current_model=system_ai_name(current_model),
        recommended_model=system_ai_name(winner),
        baseline_score=float(result.baseline_score),
        best_score=float(result.best_score),
        model_scores=_model_scores(result, service),
        train_records=len(train),
        val_records=len(val),
    )


@dataclass
class JobConfig:
    """Everything the job needs, passed to the runner as one JSON parameter."""

    upgrade_id: str
    service: str
    framework: str
    candidates: list[str]
    trace_experiment: str
    trace_limit: int
    budget: Optional[int]
    judge_model: str
    weights: tuple[float, float, float]

    def to_param(self) -> str:
        return json.dumps({**self.__dict__, "weights": list(self.weights)})

    @classmethod
    def from_param(cls, raw: str) -> "JobConfig":
        data = json.loads(raw)
        data["weights"] = tuple(data["weights"])
        return cls(**data)


def job_main(argv: Sequence[str]) -> None:
    """The job's entrypoint: ``<project root> <JobConfig JSON>``. Records the report on an MLflow run."""
    import mlflow  # noqa: PLC0415 - job-side dependency

    from databricks_agentkit.runtime import model_services  # noqa: PLC0415
    from databricks_agentkit.runtime.workspace import workspace_client  # noqa: PLC0415

    root, config = pathlib.Path(argv[0]), JobConfig.from_param(argv[1])
    mlflow.set_tracking_uri("databricks")
    mlflow.set_experiment(upgrade_experiment_name(config.trace_experiment))
    with mlflow.start_run(run_name=f"model-upgrade-{config.upgrade_id}") as run:
        mlflow.set_tags(
            {UPGRADE_ID_TAG: config.upgrade_id, "agentbricks.model_service": config.service}
        )
        mlflow.log_params(
            {
                "candidates": ",".join(config.candidates),
                "trace_limit": config.trace_limit,
                "budget": config.budget or "auto",
                "judge_model": config.judge_model,
                "weights": ",".join(str(w) for w in config.weights),
            }
        )
        current = model_services.get_model(workspace_client(), config.service)
        report = run_upgrade(
            root=root,
            framework=AgentFramework(config.framework),
            service=config.service,
            current_model=current,
            candidates=config.candidates,
            traces=load_traces(None, config.trace_experiment, config.trace_limit),
            budget=config.budget,
            judge_model=config.judge_model,
            weights=config.weights,
        )
        mlflow.set_tag(REPORT_TAG, json.dumps(report.to_json()))
        print(f"Upgrade report (MLflow run {run.info.run_id}): {json.dumps(report.to_json())}")


# --- submitting and reading back (CLI side) ------------------------------------------


def upgrade_requirement() -> str:
    """The `databricks-agentbricks` requirement the job installs: this CLI's version unless overridden."""
    override = os.getenv(UPGRADE_REQUIREMENT_ENV)
    if override:
        return override
    from importlib.metadata import version  # noqa: PLC0415

    return f"databricks-agentbricks[upgrade]=={version('databricks-agentbricks')}"


def workspace_project_path(user: str, project_name: str) -> str:
    """Where `models upgrade` syncs the project: its own folder, never the deployed app's source."""
    return f"/Workspace/Users/{user}/agentbricks_model_upgrades/{project_name}"


def submit_upgrade_run(
    client,
    *,
    workspace_path: str,
    config: JobConfig,
    timeout_hours: float = DEFAULT_TIMEOUT_HOURS,
) -> tuple[int, Optional[str]]:
    """Upload the runner and submit the serverless one-time run. Returns ``(run_id, run_page_url)``.

    The project must already be synced to ``workspace_path``.
    """
    runner_path = f"{workspace_path}/.agentbricks/model_upgrade_job.py"
    client.upload_workspace_file(runner_path, _RUNNER)
    run_id = client.submit_serverless_python_run(
        run_name=f"agentbricks models upgrade · {config.service}",
        python_file=runner_path,
        parameters=[workspace_path, config.to_param()],
        dependencies=[workspace_path, upgrade_requirement()],
        environment_version=SERVERLESS_ENVIRONMENT_VERSION,
        timeout_seconds=int(timeout_hours * 3600),
        tags={UPGRADE_ID_TAG.replace(".", "_"): config.upgrade_id},
    )
    run = client.get_run(run_id)
    return run_id, getattr(run, "run_page_url", None)


def fetch_report(
    profile: Optional[str], trace_experiment: str, upgrade_id: str
) -> Optional[UpgradeReport]:
    """The report a finished job recorded on its MLflow run, or None if it hasn't recorded one."""
    from databricks_agentbricks.cli import tracing  # noqa: PLC0415 - avoid import cycle

    mlflow = tracing._mlflow()
    tracing._set_tracking_uri(mlflow, profile)
    runs = mlflow.search_runs(
        experiment_names=[upgrade_experiment_name(trace_experiment)],
        filter_string=f"tags.`{UPGRADE_ID_TAG}` = '{upgrade_id}'",
        output_format="list",
    )
    for run in runs:
        raw = run.data.tags.get(REPORT_TAG)
        if raw:
            return UpgradeReport.from_json(json.loads(raw))
    return None


# --- history (runs, switches, rollback) ---------------------------------------------


def read_history(root: pathlib.Path) -> dict[str, list[dict[str, Any]]]:
    """The project's upgrade history: submitted ``runs`` and model-service ``changes``."""
    path = root / HISTORY_PATH
    try:
        history = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return {"runs": [], "changes": []}
    except (OSError, json.JSONDecodeError) as exc:
        raise AgentCliError(f"Could not read model upgrade history at {path}: {exc}.") from exc
    if not isinstance(history, dict):
        return {"runs": [], "changes": []}
    return {"runs": list(history.get("runs") or []), "changes": list(history.get("changes") or [])}


def _write_history(root: pathlib.Path, history: dict[str, list[dict[str, Any]]]) -> None:
    path = root / HISTORY_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(history, indent=2) + "\n", encoding="utf-8")


def record_run(root: pathlib.Path, entry: dict[str, Any]) -> None:
    """Append one submitted upgrade run."""
    history = read_history(root)
    history["runs"].append({"timestamp": int(time.time()), **entry})
    _write_history(root, history)


def update_run(root: pathlib.Path, upgrade_id: str, **fields: Any) -> None:
    """Merge ``fields`` into the recorded run ``upgrade_id`` (e.g. its final state and report)."""
    history = read_history(root)
    for run in history["runs"]:
        if run.get("upgrade_id") == upgrade_id:
            run.update(fields)
    _write_history(root, history)


def record_change(
    root: pathlib.Path,
    *,
    service: str,
    previous: Optional[str],
    model: str,
    reason: str,
    report: Optional[UpgradeReport] = None,
) -> None:
    """Append one repoint of ``service`` (``previous`` → ``model``) to the project's history."""
    entry: dict[str, Any] = {
        "timestamp": int(time.time()),
        "model_service": service,
        "previous_model": previous,
        "model": model,
        "reason": reason,
    }
    if report is not None:
        entry["baseline_score"] = report.baseline_score
        entry["best_score"] = report.best_score
    history = read_history(root)
    history["changes"].append(entry)
    _write_history(root, history)
